import SubpageHero from "@/app/components/subpage-hero";
import Footer from "@/app/pages/footer";
import Form from "@/app/pages/form";
import { Metadata } from "next";

import React from "react";

export const metadata: Metadata = {
  title: "Contact | TLC Contracting",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <SubpageHero title="Contact Us" stitle="" cta="" ctaUrl="#works" />
      <Form />
      <Footer />
    </div>
  );
};

export default page;
