import Container from "@/app/components/container";
import Navbar from "@/app/components/navbar";
import SubpageHero from "@/app/components/subpage-hero";
import Footer from "@/app/pages/footer";
import Form from "@/app/pages/form";
import { Metadata } from "next";

import React from "react";

export const metadata: Metadata = {
  title: "Free Estimate | TLC Contracting",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <SubpageHero
        title="GET YOUR FREE"
        stitle="ESTIMATE NOW!"
        cta=""
        ctaUrl="#works"
      />
      <Form />
      <Footer />
    </div>
  );
};

export default page;
