import SubpageHero from "@/app/components/subpage-hero";
import Image from "next/image";

import { Metadata } from "next";

import React from "react";

export const metadata: Metadata = {
  title: "Services | TLC Contracting",
  description: "Generated by create next app",
};

const serviceList = [
  {
    icon: "renovation",
    url: "renovation",
    title: "Renovation",
    description:
      "We manage other contractors such as plumbers, carpenter, electricians.",
    img: "renovation",
  },
  {
    icon: "plumbing",
    url: "plumbing",
    title: "Plumbing",
    description:
      "We manage other contractors such as plumbers, carpenter, electricians.",
    img: "plumbing",
  },
  {
    icon: "carpentry",
    url: "carpentry",
    title: "Carpentry",
    description:
      "We manage other contractors such as plumbers, carpenter, electricians.",
    img: "carpentry",
  },
  {
    icon: "drywall",
    url: "drywall",
    title: "Drywall",
    description:
      "We manage other contractors such as plumbers, carpenter, electricians.",
    img: "drywall",
  },
  {
    icon: "tiling",
    url: "tiling",
    title: "Tiling",
    description:
      "We manage other contractors such as plumbers, carpenter, electricians.",
    img: "tiling",
  },
  {
    icon: "painting",
    url: "painting",
    title: "Painting",
    description:
      "We manage other contractors such as plumbers, carpenter, electricians.",
    img: "painting",
  },
];

const page = () => {
  return (
    <div>
      <SubpageHero
        title="Our Offered"
        stitle="SERVICES"
        cta=""
        ctaUrl="#works"
      />
      <div className="m-auto max-w-[1800px] px-5 py-20 sm:px-10">
        <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">
          {serviceList.map((service) => (
            <a
              className=""
              href={`/services/${service.url}`}
              key={service.title}
            >
              <div className="group relative h-[400px] overflow-hidden rounded-xl md:h-[500px]">
                <Image
                  src={`/assets/services/images/${service.img}.jpg`}
                  alt={service.title}
                  fill
                  className="object-cover transition-all duration-[300ms] group-hover:scale-125"
                />
                <div className="absolute z-10 h-full w-full bg-[#111] opacity-70 transition-all duration-[300ms] group-hover:rotate-180 group-hover:scale-0" />
                <div className="absolute bottom-[-25px] left-6 z-20 transition-all duration-300 group-hover:bottom-10 sm:left-10">
                  <div className="mb-4 flex items-center gap-4">
                    <Image
                      src={`/assets/services/icon/${service.icon}.svg`}
                      alt={service.title + " Icon"}
                      width={42}
                      height={42}
                      className="h-8 w-8 text-white sm:h-12 sm:w-12"
                    />
                    <h1 className="text-2xl font-bold text-white sm:text-3xl lg:text-4xl">
                      {service.title}
                    </h1>
                  </div>
                  <p className="inline bg-black text-sm font-semibold text-white opacity-0 transition-all group-hover:opacity-100 sm:text-base">
                    {service.description}
                  </p>
                </div>
              </div>
            </a>
          ))}
        </div>
      </div>
    </div>
  );
};

export default page;
