import type { Metadata } from "next";

import SubpageHero from "@/app/components/subpage-hero";
import Form from "@/app/pages/form";
import Footer from "@/app/pages/footer";
import Container from "@/app/components/container";

export const metadata: Metadata = {
  title: "Carpentry Services in Victoria | TLC Contracting",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <SubpageHero
        title="Carpenters"
        stitle="In Victoria"
        cta="View Work"
        ctaUrl="#works"
      />
      <Container className="bg-[#]">
        <h1></h1>
      </Container>
    </div>
  );
};

export default page;
